"""video”

Revision ID: e8e4e987d7d5
Revises: 6e22dc5a5ff2
Create Date: 2026-09-01 00:34:05.272955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e4e987d7d5'
down_revision: Union[str, Sequence[str], None] = '6e22dc5a5ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('consultation_type', sa.String(length=20), nullable=False, server_default='in_person'))
    op.add_column('appointments', sa.Column('video_room_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'video_room_id')
    op.drop_column('appointments', 'consultation_type')
    # ### end Alembic commands ###
